# Generated by Django 5.2.7 on 2025-11-04 21:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='JogadorCampo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('OffensiveZone', 'OffensiveZone'), ('NeutralZone', 'NeutralZone'), ('DefensiveZone', 'DefensiveZone')], max_length=20)),
                ('club', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=120)),
                ('photo_path', models.CharField(max_length=500)),
                ('overall', models.IntegerField(default=0)),
                ('attack', models.IntegerField(default=0)),
                ('passing', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'jogadores_campo',
                'ordering': ['-overall', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JogadorGoleiro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(default='GoalkeeperZone', max_length=20)),
                ('club', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=120)),
                ('photo_path', models.CharField(max_length=500)),
                ('overall', models.IntegerField(default=0)),
                ('handling', models.IntegerField(default=0)),
                ('positioning', models.IntegerField(default=0)),
                ('reflex', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'jogadores_goleiros',
                'ordering': ['-overall', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('image_path', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'sistemas_packs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SistemasUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coins', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sistemas_users',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='PackEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player_type', models.CharField(choices=[('field', 'FieldPlayer'), ('gk', 'Goalkeeper')], max_length=8)),
                ('player_id', models.UUIDField()),
                ('weight', models.IntegerField(default=1)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='sistemas.pack')),
            ],
            options={
                'db_table': 'sistemas_packentry',
                'ordering': ['-weight'],
                'unique_together': {('pack', 'player_type', 'player_id')},
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('object_id', models.CharField(max_length=36)),
                ('qty', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='sistemas.sistemasuser')),
            ],
            options={
                'db_table': 'sistemas_inventory',
                'ordering': ['-obtained_at'],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
