# Generated by Django 5.2.7 on 2025-10-30 16:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JogadorCampo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('OffensiveZone', 'OffensiveZone'), ('NeutralZone', 'NeutralZone'), ('DefensiveZone', 'DefensiveZone'), ('GoalkeeperZone', 'GoalkeeperZone')], max_length=20)),
                ('club', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=120)),
                ('photo_path', models.CharField(max_length=500)),
                ('overall', models.IntegerField(default=0)),
                ('attack', models.IntegerField(default=0)),
                ('passing', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('aggression', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'jogadores_campo',
                'ordering': ['-overall', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SistemasUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coins', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sistemas_users',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_by', to='sistemas.jogadorcampo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='sistemas.sistemasuser')),
            ],
            options={
                'db_table': 'sistemas_inventory',
                'ordering': ['-obtained_at'],
                'unique_together': {('user', 'player')},
            },
        ),
    ]
