# Generated by Django 5.2.7 on 2025-11-10 23:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='AI Team', max_length=200)),
                ('slots', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sistemas_ai_team',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('home_is_user', models.BooleanField(default=True)),
                ('events', models.JSONField(blank=True, default=list)),
                ('score_home', models.IntegerField(default=0)),
                ('score_away', models.IntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('ai_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistemas.aiteam')),
                ('user_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistemas.team')),
            ],
            options={
                'db_table': 'sistemas_match',
                'ordering': ['-created_at'],
            },
        ),
    ]
